OPENQASM 3.0;
include "stdgates.inc";
gate _circuit_159 _gate_q_0 {
  s _gate_q_0;
  s _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
  s _gate_q_0;
  h _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
  t _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
}
gate _circuit_158 _gate_q_0 {
  sdg _gate_q_0;
  h _gate_q_0;
  _circuit_159 _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
}
gate _circuit_165 _gate_q_0 {
  sdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  sdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  sdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  sdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  sdg _gate_q_0;
  h _gate_q_0;
  tdg _gate_q_0;
  sdg _gate_q_0;
  h _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
  s _gate_q_0;
  h _gate_q_0;
  sdg _gate_q_0;
  sdg _gate_q_0;
}
gate _circuit_164 _gate_q_0 {
  sdg _gate_q_0;
  h _gate_q_0;
  _circuit_165 _gate_q_0;
  h _gate_q_0;
  s _gate_q_0;
}
qubit[2] q;
_circuit_158 q[1];
cx q[0], q[1];
_circuit_164 q[1];
cx q[0], q[1];
